version: "3.7"
services:
  headlessmql:
    image: keyyuki/headless-mt4:1.0
    volumes:
      - ./mt4:/home/winer/.wine/drive_c/mt4
      - ./screenshots:/tmp/screenshots
    cap_add:
      - SYS_PTRACE
    ports:
      - 5900:5900

    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
