version: "3.7"
services:
  headlessmql:
    image: nevmerzhitsky/headless-metatrader4
    volumes:
      - ./mt4:/home/winer/.wine/drive_c/mt4
      - ./screenshots:/tmp/screenshots
    cap_add:
      - SYS_PTRACE
    command:
      - /docker/run_mt.sh
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
